# Generated by Django 4.1.7 on 2023-02-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimagemodel',
            name='productimage',
            field=models.ImageField(default='defaultProduct.jpg', upload_to='profileImage/%Y/%m/%d/'),
        ),
    ]
